loony-tunes-master/MusicApp/urls.py
from django.contrib import admin
from django.urls import include,  path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('',views.homePage, name='home_page'),
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loony-tunes-master/music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    path('', views.IndexView.as_view(), name="index"),

    # /music/<album_id>/
    path('<int:pk>/', views.DetailView.as_view(), name="detail"),

    # /music/album/add/
    path('album/add', views.AlbumCreate.as_view(), name="album-add"),

    # /music/album/<album_id>/
    path('album/<int:pk>/', views.AlbumUpdate.as_view(), name="album-update"),

    # /music/album/<album_id>/delete/
    path('album/<int:pk>/delete/', views.AlbumDelete.as_view(), name="album-delete"),

    # /music/register/
    path('register/', views.UserFormView.as_view(), name="register"),

    # /music/<album_id>/add_songs/
    path('<int:album_id>/add_songs/', views.add_song, name='song-add'),

    # /music/<album_id>/delete_song/<song_id>/
    path('<int:album_id>/delete_song/<int:song_id>', views.delete_song, name='song-delete'),

    # /music/songs/<filter_by>/
    path('songs/<filter_by>/', views.songs, name='songs'),

    # /music/login/
    path('login/', views.login_user, name='login_user'),

    # /music/logout/
    path('logout/', views.logout_user, name='logout_user'),

    # /music/<song_id>/favorite/
    path('<int:song_id>/favorite/', views.favorite_song, name='favorite'),

    # /music/<album_id>/favorite_album/
    path('<int:album_id>/favorite_album/', views.favorite_album, name='favorite_album'),

]

loony-tunes-master/music/models.py
from django.db import models
from django.contrib.auth.models import Permission, User
from django.urls import reverse

# Create your models here.


class Album(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.DO_NOTHING)
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + " - " + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    audio_file = models.FileField(default='')
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

loony-tunes-master/music/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Song


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class SongForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ['song_title', 'audio_file']

loony-tunes-master/music/views.py
from django.http import JsonResponse, HttpResponse
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from django.urls import reverse_lazy
from .models import Album, Song
from .forms import UserForm, SongForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.contrib import messages

AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'albums'
    login_url = '/music/login/'

    def get(self, request, *args, **kwargs):
        query = request.GET.get("q")
        print("Q" + str(query))
        albums = Album.objects.filter(user=self.request.user)
        if query:
            song_results = Song.objects.all()
            if query:
                albums = albums.filter(
                    Q(album_title__icontains=query) |
                    Q(artist__icontains=query)
                ).distinct()
                song_results = song_results.filter(
                    Q(song_title__icontains=query)
                ).distinct()
                return render(request, 'music/index.html', {
                    'albums': albums,
                    'searcher': True,
                    'songs': song_results,
                })
        else:
            return render(request, 'music/index.html', {
                'albums': albums,
            })

    def get_queryset(self):
        return Album.objects.filter(user=self.request.user.id)


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Album
    template_name = 'music/detail.html'
    login_url = '/music/login/'


class AlbumCreate(LoginRequiredMixin, CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

    def form_valid(self, form):
        form.instance.user = self.request.user
        file_type = form.instance.album_logo.url.split('.')[-1]
        file_type = file_type.lower()
        form_error = form.errors
        if file_type not in IMAGE_FILE_TYPES:
            form_error['album_logo'] = "INVALID FILE SELECTED. FILE MUST HAVE EXTENSION OF ['.jpg', '.png', 'jpeg']"
            return super(AlbumCreate, self).form_invalid(form)
        return super(AlbumCreate, self).form_valid(form)


class AlbumUpdate(LoginRequiredMixin, UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']
    login_url = '/music/login/'

    def form_valid(self, form):
        file_type = form.instance.album_logo.url.split('.')[-1]
        file_type = file_type.lower()
        form_error = form.errors
        if file_type not in IMAGE_FILE_TYPES:
            form_error['album_logo'] = "INVALID FILE SELECTED. FILE MUST HAVE EXTENSION OF ['.jpg', '.png', 'jpeg']"
            return super(AlbumUpdate, self).form_invalid(form)
        return super(AlbumUpdate, self).form_valid(form)


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')
    login_url = '/music/login/'


class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            # clean/normalised data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns user object if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form})


def add_song(request, album_id):
    if not request.user.is_authenticated:
        return redirect('music:login_user')
    else:
        form = SongForm(request.POST or None, request.FILES or None)
        album = get_object_or_404(Album, pk=album_id)
        if form.is_valid():
            albums_songs = album.song_set.all()
            for s in albums_songs:
                if s.song_title == form.cleaned_data.get("song_title"):
                    context = {
                        'album': album,
                        'form': form,
                        'error_message': 'You already added that song',
                    }
                    return render(request, 'music/add_song.html', context)
            song = form.save(commit=False)
            song.album = album
            song.audio_file = request.FILES['audio_file']
            file_type = song.audio_file.url.split('.')[-1]
            file_type = file_type.lower()

            if file_type not in AUDIO_FILE_TYPES:
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'Audio file must be WAV, MP3, or OGG',
                }
                return render(request, 'music/add_song.html', context)

            song.save()
            return render(request, 'music/detail.html', {'album': album})
        context = {
            'album': album,
            'form': form,
        }
        return render(request, 'music/add_song.html', context)


def delete_song(request, album_id, song_id):
    if not request.user.is_authenticated:
        return redirect('music:login_user')
    else:
        album = get_object_or_404(Album, pk=album_id)
        song = Song.objects.get(pk=song_id)
        song.delete()
        return redirect('music:detail', album.pk)


def songs(request, filter_by):
    if not request.user.is_authenticated:
        return redirect('music:login_user')
    else:
        try:
            song_ids = []
            for album in Album.objects.filter(user=request.user):
                for song in album.song_set.all():
                    song_ids.append(song.pk)
            users_songs = Song.objects.filter(pk__in=song_ids)
            if filter_by == 'favorites':
                users_songs = users_songs.filter(is_favorite=True)
        except Album.DoesNotExist:
            users_songs = []
        return render(request, 'music/songs.html', {
            'song_list': users_songs,
            'filter_by': filter_by,
        })


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                return redirect('music:index')
            else:
                return render(request, 'music/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'music/login.html', {'error_message': 'Invalid login'})
    return render(request, 'music/login.html')


def logout_user(request):
    logout(request)
    return redirect('home_page')


def favorite_song(request, song_id):
    song = get_object_or_404(Song, pk=song_id)
    current_url = request.resolver_match.view_name
    print(current_url)
    try:
        if song.is_favorite:
            song.is_favorite = False
        else:
            song.is_favorite = True
        song.save()
    except (KeyError, Song.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def favorite_album(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        if album.is_favorite:
            album.is_favorite = False
        else:
            album.is_favorite = True
        album.save()
    except (KeyError, Album.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})

loony-tunes-master/music/templates/music/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Loony Tunes
        {% endblock  %}
    </title>
    <link rel="shortcut icon" type="image/png" href="{%  static 'music/images/favicon.ico' %}"/>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <script   src="https://code.jquery.com/jquery-1.12.4.min.js"   integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="   crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
    <script src="{% static 'music/script.js' %}"></script>
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

             <div class="navbar-header">
                 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavbar">
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                 </button>
                 <a class="navbar-brand" href="{% url 'music:index' %}"> Loony Tunes </a>
             </div>

            <div class="collapse navbar-collapse" id="topNavbar">
                <ul class="nav navbar-nav">
                    <li class="{% block albums_active %}{% endblock %}">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                        </a>
                    </li>
                    <li class="{% block songs_active %}{% endblock %}">
                        <a href="{% url 'music:songs' 'all' %}">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                        </a>
                    </li>
                </ul>

                <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'music:index' %}">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                    </div>
                    <button type="submit" class="btn btn-default"> Search </button>
                </form>

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'music:album-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'music:logout_user' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block page %}
    {% endblock %}

</body>
</html>

loony-tunes-master/music/templates/music/detail.html
{% extends 'music/base.html' %}

{% load static %}


{% block title %}
    {{ album.album_title }}
{% endblock %}


{% block page %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }}</h1>
                    <h2>{{ album.artist }}</h2>
                    <h3><small>{{ album.genre }}</small></h3>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'music:song-add' album.id %}">Add a New Song</a></li>
                <li role="presentation"><a href="{% url 'music:album-update' album.id %}">Edit Album</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a target="_blank" href="{{ song.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="{% url 'music:song-delete' album.id song.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}



{#{% block page %}#}
{##}
{#    <h1> {{ album.album_title }} </h1>#}
{#    <h3> {{ album.artist }} </h3>#}
{#    <img src="{{ album.album_logo }}">#}
{#    <br>#}
{#    {% for song in album.song_set.all %}#}
{#        {{ song.song_title }}#}
{#        <br>#}
{#    {% endfor %}#}
{##}
{#{% endblock %}#}

loony-tunes-master/music/templates/music/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger lead">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

loony-tunes-master/music/templates/music/index.html
{% extends 'music/base.html' %}

{% load extra_tags %}

{% block title %}
    Loony Tunes
{% endblock %}

{% block albums_active %}
    active
{% endblock %}

{% get_mod2 0 as count %}

{% block page %}
    <div class="albums-container container-fluid">

        <!-- Albums -->
        <div class="row">
            <div class="col-sm-12">
                <h3>{{ user.username }}'s Albums</h3>
            </div>
        </div>

        <div class="row">
            {% if albums %}
                <div class="list-group">
                    {% for album in albums %}
                        {% get_mod2 forloop.counter0 as count %}

                        {% if not count %}
                            <div class="list-group-item">
                            <div class="row">
                        {% endif %}

                    <div class="col-sm-12 col-md-12 col-lg-6"
                         style="margin:-1px 0 0 -1px; border-left: 1px solid rgba(0, 0, 0, 0.125);border-right: 1px solid rgba(0, 0, 0, 0.125);">
                        <div class="col-sm-3">
                            <a href="{% url 'music:detail' album.id %}">
                                <img src="{{ album.album_logo.url }}" class="img-responsive">
                            </a>
                        </div>
                        <div class="col-sm-6">
                            <div class="row">
                                <div class="col-xs-10">
                                    <a href="{% url 'music:detail' album.id %}">
                                        <h2 class="text-wrap text-break"
                                            style="overflow-wrap: break-word; word-break: break-word">{{ album.album_title }}</h2>
                                        <h4>{{ album.artist }}</h4>
                                    </a>
                                </div>
                                <div class="col-xs-2">
                                    <!-- Favorite Album -->
                                    <a href="{% url 'music:favorite_album' album.id %}"
                                       class="btn btn-default btn-md btn-favorite"
                                       role="button">
                                        <span class="glyphicon glyphicon-heart {% if album.is_favorite %}active{% endif %}"></span>
                                    </a>
                                </div>
                            </div>

                        </div>
                        <div class="col-sm-3">
                            <div class="row">
                                <div class="col-sm-12">
                                    <!-- View Details -->
                                    <a href="{% url 'music:detail' album.id %}"
                                       class="btn btn-primary btn-sm"
                                       role="button" style="width: 100%;"> View </a>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-12">
                                    <!-- Delete Album -->
                                    <form action="{% url 'music:album-delete' album.id %}" method="post"
                                          style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="album_id" value="{{ album.id }}"/>
                                        <button style="width: 100%;margin-top: 10px" type="submit"
                                                class="btn btn-default btn-sm">
                                            <span class="glyphicon glyphicon-trash"> Delete </span>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% if count %}
                        </div>
                        </div>
                    {% endif %}


                        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                    {% endfor %}
                </div>
                </div>
            {% elif searcher %}
                <div class="col-sm-12">
                    <br>


                    <span class="glyphicon glyphicon-exclamation-sign"></span>&nbsp; No Matching Albums Found

                </div>
            {% else %}
                <div class="col-sm-12">
                    <br>
                    <a href="{% url 'music:album-add' %}">
                        <button type="button" class="btn btn-success">
                            <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                        </button>
                    </a>
                </div>
            {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    {% if songs %}
        <div class="row" style="padding-top: 50px">
            <div class="col-sm-12" style="padding-bottom: 20px">
                <h3>{{ user.username }}'s Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Song Title</th>
                                <th>Artist</th>
                                <th>Audio File</th>
                                <th>Album</th>
                                <th>Favorite</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for song in songs %}
                                <tr>
                                    <td>{{ song.song_title }}</td>
                                    <td>{{ song.album.artist }}</td>
                                    <td>
                                        <a target="_blank" href="{{ song.audio_file.url }}">
                                            <button type="button" class="btn btn-success btn-xs">
                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                            </button>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'music:detail' song.album.id %}">
                                            <img src="{{ song.album.album_logo.url }}" class="img-responsive"
                                                 style="width: 20px; float: left; margin-right: 10px;"/>
                                        </a>
                                        <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                    </td>
                                    <td>
                                        <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span
                                                class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
            {% elif searcher %}
        <div class="row" style="padding-top: 50px">
            <div class="col-sm-12">
                <h3>{{ user.username }}'s Songs</h3>
            </div>
        </div>
            <div class="row">
            <div class="col-sm-12">
                <br>
                <span class="glyphicon glyphicon-exclamation-sign"></span>&nbsp; No Matching Songs Found
            </div>
            </div>


    {% endif %}


{% endblock %}


{#{% block page %}#}
{##}
{#    <h1> ALBUM LIST </h1>#}
{#    {% if all_albums %}#}
{#        <ul>#}
{#            {% for album in all_albums %}#}
{#                <li><a href="{% url 'music:detail' album.id %}"> {{ album.album_title }} </a></li>#}
{#            {% endfor %}#}
{#        </ul>#}
{#    {% else %}#}
{#        <h2> No Albums Found </h2>#}
{#    {% endif %}#}
{##}
{#{% endblock %}#}

loony-tunes-master/music/templates/music/songs.html
{% extends 'music/base.html' %}
{% block title %}All Songs{% endblock %}
{% block songs_active %}active{% endblock %}

{% block page %}
<div class="container-fluid songs-container">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" {% if filter_by == 'all' %}class="active"{% endif %}><a href="{% url 'music:songs' 'all' %}">View All</a></li>
                <li role="presentation" {% if filter_by == 'favorites' %}class="active"{% endif %}><a href="{% url 'music:songs' 'favorites' %}">View Favorites</a></li>
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Song Title</th>
                                <th>Artist</th>
                                <th>Audio File</th>
                                <th>Album</th>
                                <th>Favorite</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for song in song_list %}
                                <tr>
                                    <td>{{ song.song_title }}</td>
                                    <td>{{ song.album.artist }}</td>
                                    <td>
                                        <a target="_blank" href="{{ song.audio_file.url }}">
                                            <button type="button" class="btn btn-success btn-xs">
                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                            </button>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'music:detail' song.album.id %}">
                                            <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                    </td>
                                    <td>
                                        <a href="{% url 'music:favorite' song.id %}"
                                           class="btn-favorite">
                                            <span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}